export interface ProductData {
  _id: string
  name: string
  price: string
  category: 'Earrings' | 'Necklaces' | 'Bracelets' | 'Jewellery Sets'
  story: string
  material: string
  description: string
  details: string[]
  materials: string
  care: string
  options: string[]
  images: string[]
  featured: boolean
  createdAt: string
  updatedAt: string
}

export type SeedProduct = Omit<ProductData, '_id' | 'createdAt' | 'updatedAt'>

export const seedProducts: SeedProduct[] = [
  {
    name: 'AMAPELS SIGNATURE HOOP',
    price: '₦250,000',
    category: 'Earrings',
    story: 'Statement Earrings',
    material: 'Gold-tone finish',
    description: 'A beautiful hoop earring that adds warmth and confidence to any outfit, perfect for both everyday wear and special occasions.',
    details: [
      'Lightweight and comfortable to wear',
      'Polished gold-tone finish',
      'Secure clasp for all-day comfort',
      'Versatile for daily and occasion wear',
    ],
    materials: 'Gold-tone alloy with stone detail',
    care: 'Store in a dry place and wipe gently with a soft cloth after wearing.',
    options: ['Gold Finish', 'Gift Box'],
    images: [
      '/images/sabrianna-Y_bxfTa_iUA-unsplash.jpg',
      '/images/gabriel-ogulu-r0bH4hAVBmk-unsplash.jpg',
      '/images/evie-martinez-mCjEVrBS1bM-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'GOLDEN PEARL DROP EARRINGS',
    price: '₦180,000',
    category: 'Earrings',
    story: 'Elegant Drops',
    material: 'Pearl & Gold',
    description: 'Elegant pearl drop earrings with gold accents, perfect for adding sophistication to any ensemble.',
    details: [
      'Genuine freshwater pearls',
      '14K gold plating',
      'Secure hook closure',
      'Hypoallergenic materials',
    ],
    materials: '14K gold-plated brass with freshwater pearls',
    care: 'Avoid contact with water and perfumes. Store in jewelry pouch.',
    options: ['Gold Pearl', 'Silver Pearl'],
    images: [
      '/images/pexels-vedat-28933799.jpg',
      '/images/pexels-vedat-29043373.jpg',
    ],
    featured: true,
  },
  {
    name: 'DIAMOND STUD COLLECTION',
    price: '₦320,000',
    category: 'Earrings',
    story: 'Timeless Elegance',
    material: 'Diamond & White Gold',
    description: 'Classic diamond studs that shine with every movement. A must-have for every jewelry collection.',
    details: [
      'AAA cubic zirconia stones',
      'White gold plated',
      'Butterfly back closure',
      'Gift box included',
    ],
    materials: 'White gold plated sterling silver with cubic zirconia',
    care: 'Clean with soft cloth. Store separately to avoid scratches.',
    options: ['Small', 'Medium', 'Large'],
    images: [
      '/images/andres-vera-202NAwjisYA-unsplash.jpg',
      '/images/brian-wangenheim--5T5yMvZ2-E-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'ROSE GOLD HEART STUDS',
    price: '₦145,000',
    category: 'Earrings',
    story: 'Love & Romance',
    material: 'Rose Gold',
    description: 'Delicate heart-shaped studs in rose gold, perfect for expressing love and affection.',
    details: [
      'Rose gold plated',
      'Heart design',
      'Push back closure',
      'Perfect gift for loved ones',
    ],
    materials: 'Rose gold plated brass',
    care: 'Wipe with soft cloth after use. Avoid harsh chemicals.',
    options: ['Rose Gold'],
    images: [
      '/images/carlos-esteves-1MWbwTaeJIA-unsplash.jpg',
      '/images/edgar-soto-o87CUS_uDiQ-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'CRYSTAL CHANDELIER EARRINGS',
    price: '₦275,000',
    category: 'Earrings',
    story: 'Red Carpet Ready',
    material: 'Crystal & Gold',
    description: 'Stunning chandelier earrings with cascading crystals that catch the light beautifully.',
    details: [
      'Swarovski crystals',
      'Gold tone finish',
      'Statement piece',
      'Perfect for special events',
    ],
    materials: 'Gold-tone brass with Swarovski crystals',
    care: 'Handle with care. Store in protective box.',
    options: ['Clear Crystal', 'Champagne Crystal'],
    images: [
      '/images/evie-martinez-mCjEVrBS1bM-unsplash.jpg',
      '/images/gabriel-ogulu-r0bH4hAVBmk-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'LAYERED GOLD CHAIN NECKLACE',
    price: '₦195,000',
    category: 'Necklaces',
    story: 'Modern Layers',
    material: 'Gold Chain',
    description: 'Trendy layered chain necklace that adds dimension and style to any outfit.',
    details: [
      'Three layer design',
      'Adjustable length',
      'Lobster clasp',
      'Versatile styling',
    ],
    materials: '18K gold plated stainless steel',
    care: 'Avoid water exposure. Store flat to prevent tangling.',
    options: ['Gold', 'Silver'],
    images: [
      '/images/godfred-kwakye-fOcFLNzGtd0-unsplash.jpg',
      '/images/julie-sd--Njp0M9Rzhc-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'PENDANT STATEMENT NECKLACE',
    price: '₦225,000',
    category: 'Necklaces',
    story: 'Bold & Beautiful',
    material: 'Gold & Stone',
    description: 'Eye-catching pendant necklace featuring a large statement stone in gold setting.',
    details: [
      'Large gemstone pendant',
      'Gold chain included',
      'Adjustable 16-18 inches',
      'Makes a statement',
    ],
    materials: 'Gold-plated brass with semi-precious stone',
    care: 'Remove before swimming. Clean gently with soft cloth.',
    options: ['Emerald', 'Ruby', 'Sapphire'],
    images: [
      '/images/k-studios-hbCWaqLnD_s-unsplash.jpg',
      '/images/lisa-marie-theck-pxg9jOgPzK4-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'PEARL STRAND NECKLACE',
    price: '₦285,000',
    category: 'Necklaces',
    story: 'Classic Sophistication',
    material: 'Cultured Pearls',
    description: 'Timeless pearl strand necklace that exudes elegance and grace.',
    details: [
      'AAA grade cultured pearls',
      '18 inch length',
      'Sterling silver clasp',
      'Comes in luxury box',
    ],
    materials: 'Cultured freshwater pearls with sterling silver',
    care: 'Wipe after wearing. Avoid perfumes and hairspray.',
    options: ['White', 'Cream', 'Pink'],
    images: [
      '/images/mayank-gehlot-lsxBmX8Hmwc-unsplash.jpg',
      '/images/michael-kyule-sjnV1w7TtNE-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'COIN CHARM NECKLACE',
    price: '₦165,000',
    category: 'Necklaces',
    story: 'Lucky Charm',
    material: 'Gold Coin',
    description: 'Delicate chain with lucky coin charm, perfect for everyday elegance.',
    details: [
      'Engraved coin pendant',
      'Dainty chain',
      '16 inch length',
      'Meaningful gift',
    ],
    materials: '14K gold filled chain and pendant',
    care: 'Safe for daily wear. Clean with jewelry cloth.',
    options: ['Gold', 'Rose Gold'],
    images: [
      '/images/moses-malik-roldan-7KqTvNjAZws-unsplash.jpg',
      '/images/muhammad-taha-ibrahim-DWcGIvmI30Y-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'INFINITY LOVE NECKLACE',
    price: '₦155,000',
    category: 'Necklaces',
    story: 'Endless Love',
    material: 'White Gold',
    description: 'Beautiful infinity symbol necklace representing eternal love and connection.',
    details: [
      'Infinity pendant design',
      'Micro-pave crystals',
      'White gold plated',
      'Perfect romantic gift',
    ],
    materials: 'White gold plated sterling silver with crystals',
    care: 'Keep dry. Store in anti-tarnish bag.',
    options: ['White Gold', 'Yellow Gold'],
    images: [
      '/images/pexels-ben-iwara-1033992193-27152278.jpg',
      '/images/pexels-gabriela-brasiliano-515209300-32225451.jpg',
    ],
    featured: true,
  },
  {
    name: 'CRYSTAL BANGLE BRACELET',
    price: '₦180,000',
    category: 'Bracelets',
    story: 'Sparkle & Shine',
    material: 'Crystal Detail',
    description: 'Elegant bangle bracelet adorned with sparkling crystals for maximum shine.',
    details: [
      'Pave crystal setting',
      'Hinged bangle',
      'Secure clasp',
      'Comfortable fit',
    ],
    materials: 'Gold-tone brass with Austrian crystals',
    care: 'Avoid hard impacts. Clean with damp cloth.',
    options: ['Gold', 'Silver', 'Rose Gold'],
    images: [
      '/images/pexels-howard-chin-1677264-5564051.jpg',
      '/images/pexels-sheilabox-235376934-12184920.jpg',
    ],
    featured: false,
  },
  {
    name: 'GOLD CHAIN BRACELET',
    price: '₦135,000',
    category: 'Bracelets',
    story: 'Simple Elegance',
    material: 'Gold Chain',
    description: 'Classic chain bracelet that pairs perfectly with any outfit, day or night.',
    details: [
      'Delicate chain links',
      'Adjustable sizing',
      'Lobster clasp',
      'Layer-friendly',
    ],
    materials: '18K gold plated brass',
    care: 'Safe for daily wear. Avoid moisture.',
    options: ['Thin Chain', 'Medium Chain'],
    images: [
      '/images/pexels-vedat-28933799.jpg',
      '/images/pexels-vedat-29043373.jpg',
    ],
    featured: false,
  },
  {
    name: 'PEARL CUFF BRACELET',
    price: '₦205,000',
    category: 'Bracelets',
    story: 'Modern Classic',
    material: 'Pearl & Gold',
    description: 'Contemporary cuff bracelet featuring lustrous pearls set in gold.',
    details: [
      'Three pearl accents',
      'Open cuff design',
      'One size fits most',
      'Statement piece',
    ],
    materials: 'Gold-plated brass with freshwater pearls',
    care: 'Handle gently. Store separately.',
    options: ['Gold & White Pearl', 'Gold & Black Pearl'],
    images: [
      '/images/prahant-studio-h0evAOsNNtg-unsplash.jpg',
      '/images/sabrianna-Y_bxfTa_iUA-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'TENNIS BRACELET',
    price: '₦295,000',
    category: 'Bracelets',
    story: 'Classic Glamour',
    material: 'Diamond Simulant',
    description: 'Iconic tennis bracelet with brilliant cut stones that sparkle from every angle.',
    details: [
      'Continuous row of stones',
      'Secure box clasp',
      '7 inch length',
      'Timeless design',
    ],
    materials: 'Sterling silver with cubic zirconia stones',
    care: 'Professional cleaning recommended annually.',
    options: ['Silver', 'Gold Plated'],
    images: [
      '/images/theresa-ude-01hjEW7Hc-8-unsplash.jpg',
      '/images/theresa-ude-bFSMzNAij8I-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'CHARM BRACELET SET',
    price: '₦175,000',
    category: 'Bracelets',
    story: 'Tell Your Story',
    material: 'Mixed Metals',
    description: 'Personalize your style with this charm bracelet featuring interchangeable charms.',
    details: [
      'Five starter charms included',
      'Add more charms anytime',
      'Expandable chain',
      'Meaningful gift',
    ],
    materials: 'Mixed metal alloy with enamel details',
    care: 'Wipe clean after wearing. Store charms separately.',
    options: ['Starter Set', 'Premium Set'],
    images: [
      '/images/andres-vera-202NAwjisYA-unsplash.jpg',
      '/images/brian-wangenheim--5T5yMvZ2-E-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'GOLD RING TRIO SET',
    price: '₦185,000',
    category: 'Jewellery Sets',
    story: 'Stack & Layer',
    material: 'Gold Bands',
    description: 'Three stackable gold rings that can be worn together or separately.',
    details: [
      'Three ring sizes',
      'Thin band design',
      'Mix and match',
      'Comfortable wear',
    ],
    materials: '14K gold filled bands',
    care: 'Safe for everyday wear. Clean with jewelry solution.',
    options: ['Size 6', 'Size 7', 'Size 8'],
    images: [
      '/images/carlos-esteves-1MWbwTaeJIA-unsplash.jpg',
      '/images/edgar-soto-o87CUS_uDiQ-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'BRIDAL JEWELRY SET',
    price: '₦450,000',
    category: 'Jewellery Sets',
    story: 'Wedding Day Perfect',
    material: 'White Gold & Crystal',
    description: 'Complete bridal set including necklace, earrings, and bracelet for your special day.',
    details: [
      'Matching three-piece set',
      'Crystal embellishments',
      'White gold finish',
      'Luxury packaging',
    ],
    materials: 'White gold plated brass with Swarovski crystals',
    care: 'Professional cleaning recommended. Store in original box.',
    options: ['Complete Set'],
    images: [
      '/images/evie-martinez-mCjEVrBS1bM-unsplash.jpg',
      '/images/gabriel-ogulu-r0bH4hAVBmk-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'EVENING ELEGANCE SET',
    price: '₦325,000',
    category: 'Jewellery Sets',
    story: 'Night Out',
    material: 'Gold & Black Stone',
    description: 'Sophisticated set perfect for evening events with dramatic black stones.',
    details: [
      'Necklace and earring set',
      'Black onyx stones',
      'Gold settings',
      'Makes a statement',
    ],
    materials: 'Gold-plated brass with black onyx',
    care: 'Avoid contact with cosmetics. Wipe gently after use.',
    options: ['Two-Piece Set'],
    images: [
      '/images/godfred-kwakye-fOcFLNzGtd0-unsplash.jpg',
      '/images/julie-sd--Njp0M9Rzhc-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'PEARL JEWELRY COLLECTION',
    price: '₦385,000',
    category: 'Jewellery Sets',
    story: 'Timeless Pearl',
    material: 'Cultured Pearls',
    description: 'Elegant pearl collection with necklace, bracelet, and earrings.',
    details: [
      'AAA cultured pearls',
      'Sterling silver components',
      'Classic three-piece set',
      'Heirloom quality',
    ],
    materials: 'Cultured freshwater pearls with sterling silver',
    care: 'Last to put on, first to take off. Store separately.',
    options: ['Classic White', 'Vintage Cream'],
    images: [
      '/images/k-studios-hbCWaqLnD_s-unsplash.jpg',
      '/images/lisa-marie-theck-pxg9jOgPzK4-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'ROSE GOLD ROMANCE SET',
    price: '₦265,000',
    category: 'Jewellery Sets',
    story: 'Modern Romance',
    material: 'Rose Gold',
    description: 'Beautiful rose gold set with heart motifs perfect for romantic occasions.',
    details: [
      'Heart design theme',
      'Rose gold plating',
      'Necklace and earrings',
      'Perfect gift set',
    ],
    materials: 'Rose gold plated brass',
    care: 'Polish regularly with soft cloth. Avoid water.',
    options: ['Two-Piece Set'],
    images: [
      '/images/mayank-gehlot-lsxBmX8Hmwc-unsplash.jpg',
      '/images/michael-kyule-sjnV1w7TtNE-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'MINIMALIST GOLD SET',
    price: '₦195,000',
    category: 'Jewellery Sets',
    story: 'Less is More',
    material: 'Gold',
    description: 'Clean, minimal design set for the modern woman who loves understated elegance.',
    details: [
      'Simple geometric designs',
      'Thin delicate pieces',
      'Daily wear friendly',
      'Versatile styling',
    ],
    materials: '14K gold filled',
    care: 'Low maintenance. Safe for daily wear.',
    options: ['Two-Piece Set', 'Three-Piece Set'],
    images: [
      '/images/moses-malik-roldan-7KqTvNjAZws-unsplash.jpg',
      '/images/muhammad-taha-ibrahim-DWcGIvmI30Y-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'STATEMENT COCKTAIL SET',
    price: '₦345,000',
    category: 'Jewellery Sets',
    story: 'Party Ready',
    material: 'Mixed Crystals',
    description: 'Bold and beautiful set with oversized crystals for maximum impact.',
    details: [
      'Large statement pieces',
      'Multi-color crystals',
      'Adjustable sizing',
      'Showstopper design',
    ],
    materials: 'Gold-tone brass with mixed crystals',
    care: 'Store carefully to avoid damage. Handle with care.',
    options: ['Rainbow', 'Emerald'],
    images: [
      '/images/pexels-ben-iwara-1033992193-27152278.jpg',
      '/images/pexels-gabriela-brasiliano-515209300-32225451.jpg',
    ],
    featured: true,
  },
  {
    name: 'EVERYDAY ESSENTIALS SET',
    price: '₦145,000',
    category: 'Jewellery Sets',
    story: 'Daily Staples',
    material: 'Mixed Metals',
    description: 'Essential pieces you can wear every day without worrying about damage.',
    details: [
      'Durable construction',
      'Simple classic designs',
      'Comfortable fit',
      'Great value',
    ],
    materials: 'Stainless steel with gold plating',
    care: 'Water resistant. Easy to maintain.',
    options: ['Gold Tone', 'Silver Tone'],
    images: [
      '/images/pexels-howard-chin-1677264-5564051.jpg',
      '/images/pexels-sheilabox-235376934-12184920.jpg',
    ],
    featured: false,
  },
  {
    name: 'VINTAGE INSPIRED SET',
    price: '₦305,000',
    category: 'Jewellery Sets',
    story: 'Old World Charm',
    material: 'Antique Gold',
    description: 'Vintage-inspired jewelry set with intricate details and aged gold finish.',
    details: [
      'Victorian era design',
      'Intricate filigree work',
      'Antique gold finish',
      'Collector quality',
    ],
    materials: 'Antiqued brass with vintage crystals',
    care: 'Handle delicately. Professional cleaning recommended.',
    options: ['Complete Set'],
    images: [
      '/images/prahant-studio-h0evAOsNNtg-unsplash.jpg',
      '/images/theresa-ude-01hjEW7Hc-8-unsplash.jpg',
    ],
    featured: true,
  },
];
    description: 'A stunning bracelet with crystal details that catches the light beautifully, adding elegance to any wrist.',
    details: [
      'Beautiful crystal halo design',
      'Elegant shine for any occasion',
      'Adjustable fit for comfort',
      'Perfect for gifting someone special',
    ],
    materials: 'Silver-tone alloy with crystal stones',
    care: 'Keep away from perfume, water, and moisture to maintain the shine.',
    options: ['Silver Finish', 'Gift Box'],
    images: [
      '/images/lisa-marie-theck-pxg9jOgPzK4-unsplash.jpg',
      '/images/brian-wangenheim--5T5yMvZ2-E-unsplash.jpg',
      '/images/theresa-ude-01hjEW7Hc-8-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'GOLDEN MUSE COLLAR',
    price: '₦120,000',
    category: 'Necklaces',
    story: 'Necklaces & Sets',
    material: 'Polished gold finish',
    description: 'A beautiful neck piece that adds polish and presence to your outfit, perfect for making a statement.',
    details: [
      'Statement collar design',
      'Smooth metallic finish',
      'Great for special occasions',
      'Pairs beautifully with earrings and bracelets',
    ],
    materials: 'Polished metal finish',
    care: 'Store flat in a lined pouch and clean gently with a soft cloth.',
    options: ['Gold Finish', 'Standard Box'],
    images: [
      '/images/andres-vera-202NAwjisYA-unsplash.jpg',
      '/images/godfred-kwakye-fOcFLNzGtd0-unsplash.jpg',
      '/images/prahant-studio-h0evAOsNNtg-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'CLASSIC STUD PAIR',
    price: '₦450,000',
    category: 'Earrings',
    story: 'Modern Classics',
    material: 'Stone-set studs',
    description: 'A beautiful stud earring pair that adds timeless sparkle and elegance to your everyday look.',
    details: [
      'Classic floral-inspired design',
      'Stone-set sparkle',
      'Comfortable for all-day wear',
      'Perfect for everyday elegance',
    ],
    materials: 'Gold-tone alloy with stone setting',
    care: 'Avoid direct contact with water, lotion, or fragrance to maintain the finish.',
    options: ['Gold Finish', 'Pair'],
    images: [
      '/images/muhammad-taha-ibrahim-DWcGIvmI30Y-unsplash.jpg',
      '/images/carlos-esteves-1MWbwTaeJIA-unsplash.jpg',
      '/images/michael-kyule-sjnV1w7TtNE-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'SHELL STATEMENT SET',
    price: '₦220,000',
    category: 'Jewellery Sets',
    story: 'Cultural Edit',
    material: 'Natural shell detail',
    description: 'A coordinated jewellery set that combines natural textures with beautiful design for a standout look.',
    details: [
      'Matching necklace and earrings',
      'Natural shell-inspired details',
      'Designed to make a statement',
      'A unique conversation piece',
    ],
    materials: 'Mixed shell and metal components',
    care: 'Store separately and handle gently to preserve the natural elements.',
    options: ['Full Set', 'Gift Wrap'],
    images: [
      '/images/pexels-ben-iwara-1033992193-27152278.jpg',
      '/images/moses-malik-roldan-7KqTvNjAZws-unsplash.jpg',
      '/images/theresa-ude-bFSMzNAij8I-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'GIFTED GLOW BRACELET',
    price: '₦95,000',
    category: 'Bracelets',
    story: 'Gift Edit',
    material: 'Silver-tone finish',
    description: 'A simple, elegant bracelet perfect for everyday wear and makes a beautiful gift for someone special.',
    details: [
      'Minimal and comfortable design',
      'Soft reflective finish',
      'Easy to stack with other bracelets',
      'Perfect for gifting',
    ],
    materials: 'Silver-tone finish',
    care: 'Keep in a jewellery pouch and avoid contact with harsh surfaces.',
    options: ['Standard', 'Gift Box'],
    images: [
      '/images/theresa-ude-01hjEW7Hc-8-unsplash.jpg',
      '/images/lisa-marie-theck-pxg9jOgPzK4-unsplash.jpg',
      '/images/brian-wangenheim--5T5yMvZ2-E-unsplash.jpg',
    ],
    featured: true,
  },
  // NEW PRODUCTS USING UNUSED IMAGES
  {
    name: 'MIDNIGHT ELEGANCE EARRINGS',
    price: '₦320,000',
    category: 'Earrings',
    story: 'Evening Collection',
    material: 'Dark metal finish',
    description: 'Sophisticated drop earrings that embody elegance and mystery, perfect for evening wear and special occasions.',
    details: [
      'Dramatic drop design',
      'Dark lustrous finish',
      'Comfortable ear wire',
      'Statement piece for evenings',
    ],
    materials: 'Dark metal alloy with textured details',
    care: 'Store in individual pouches to prevent scratching.',
    options: ['Dark Finish', 'Luxury Box'],
    images: [
      '/images/edgar-soto-o87CUS_uDiQ-unsplash.jpg',
      '/images/k-studios-hbCWaqLnD_s-unsplash.jpg',
      '/images/mayank-gehlot-lsxBmX8Hmwc-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'BOHEMIAN DREAMS NECKLACE',
    price: '₦280,000',
    category: 'Necklaces',
    story: 'Free Spirit Collection',
    material: 'Mixed metals',
    description: 'A flowing, organic necklace that captures the essence of bohemian style with its natural, free-form design.',
    details: [
      'Organic, flowing design',
      'Mixed metal textures',
      'Adjustable chain length',
      'Bohemian-inspired aesthetic',
    ],
    materials: 'Mixed metal alloys with natural finish',
    care: 'Clean with soft brush and mild soap, dry thoroughly.',
    options: ['Natural Finish', 'Eco-Friendly Packaging'],
    images: [
      '/images/julie-sd--Njp0M9Rzhc-unsplash.jpg',
      '/images/pexels-gabriela-brasiliano-515209300-32225451.jpg',
      '/images/pexels-howard-chin-1677264-5564051.jpg',
    ],
    featured: false,
  },
  {
    name: 'ROYAL HERITAGE BRACELET',
    price: '₦390,000',
    category: 'Bracelets',
    story: 'Heritage Collection',
    material: 'Antique gold finish',
    description: 'A regal bracelet inspired by traditional Nigerian jewelry, featuring intricate details and rich cultural heritage.',
    details: [
      'Intricate traditional patterns',
      'Rich antique gold finish',
      'Adjustable sizing',
      'Cultural heritage design',
    ],
    materials: 'Antique gold-plated alloy with traditional motifs',
    care: 'Handle with care, store in padded box to preserve detailing.',
    options: ['Antique Gold', 'Heritage Box'],
    images: [
      '/images/pexels-sheilabox-235376934-12184920.jpg',
      '/images/pexels-vedat-28933799.jpg',
      '/images/pexels-vedat-29043373.jpg',
    ],
    featured: true,
  },
  {
    name: 'MODERN GEOMETRIC SET',
    price: '₦520,000',
    category: 'Jewellery Sets',
    story: 'Contemporary Collection',
    material: 'Brushed silver',
    description: 'A striking contemporary jewelry set featuring clean geometric lines and modern aesthetic for the fashion-forward woman.',
    details: [
      'Matching earrings and necklace',
      'Clean geometric design',
      'Brushed silver finish',
      'Contemporary minimalist style',
    ],
    materials: 'Brushed silver-tone alloy with geometric forms',
    care: 'Polish regularly with silver cloth to maintain brushed finish.',
    options: ['Complete Set', 'Designer Box'],
    images: [
      '/images/pexels-ben-iwara-1033992193-27152278.jpg',
      '/images/pexels-gabriela-brasiliano-515209300-32225451.jpg',
      '/images/pexels-howard-chin-1677264-5564051.jpg',
    ],
    featured: false,
  },
  {
    name: 'SUNRISE PENDANT NECKLACE',
    price: '₦165,000',
    category: 'Necklaces',
    story: 'Nature\'s Beauty',
    material: 'Warm gold tone',
    description: 'A delicate pendant necklace that captures the warmth of a sunrise, perfect for everyday elegance.',
    details: [
      'Delicate pendant design',
      'Warm gold tone finish',
      'Adjustable chain length',
      'Perfect for layering',
    ],
    materials: 'Gold-tone alloy with pendant detail',
    care: 'Store flat and avoid tangling with other necklaces.',
    options: ['Gold Tone', 'Standard Box'],
    images: [
      '/images/andres-vera-202NAwjisYA-unsplash.jpg',
      '/images/prahant-studio-h0evAOsNNtg-unsplash.jpg',
      '/images/godfred-kwakye-fOcFLNzGtd0-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'CRYSTAL CASCADE EARRINGS',
    price: '₦375,000',
    category: 'Earrings',
    story: 'Glamour Collection',
    material: 'Crystal and silver',
    description: 'Dazzling cascading earrings that create movement and sparkle, perfect for special occasions and celebrations.',
    details: [
      'Cascading crystal design',
      'Creates beautiful movement',
      'Silver-tone setting',
      'Perfect for special occasions',
    ],
    materials: 'Silver-tone alloy with cascading crystal elements',
    care: 'Handle gently to prevent crystal damage, store in padded compartment.',
    options: ['Silver & Crystal', 'Luxury Box'],
    images: [
      '/images/evie-martinez-mCjEVrBS1bM-unsplash.jpg',
      '/images/sabrianna-Y_bxfTa_iUA-unsplash.jpg',
      '/images/gabriel-ogulu-r0bH4hAVBmk-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'TRIBAL FUSION BRACELET',
    price: '₦215,000',
    category: 'Bracelets',
    story: 'Cultural Fusion',
    material: 'Mixed metal & beads',
    description: 'A unique bracelet that blends traditional African elements with contemporary design for a modern tribal aesthetic.',
    details: [
      'Tribal-inspired patterns',
      'Mixed metal and bead elements',
      'Comfortable stretch fit',
      'Cultural fusion design',
    ],
    materials: 'Mixed metals with natural bead accents',
    care: 'Avoid water exposure, clean gently with dry cloth.',
    options: ['Natural Finish', 'Cultural Box'],
    images: [
      '/images/moses-malik-roldan-7KqTvNjAZws-unsplash.jpg',
      '/images/theresa-ude-bFSMzNAij8I-unsplash.jpg',
      '/images/k-studios-hbCWaqLnD_s-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'PEARL RADIANCE SET',
    price: '₦680,000',
    category: 'Jewellery Sets',
    story: 'Luxury Collection',
    material: 'Pearl & gold',
    description: 'An exquisite pearl jewelry set that embodies timeless elegance and luxury, perfect for the most special occasions.',
    details: [
      'Matching pearl necklace and earrings',
      'Lustrous pearl finish',
      'Gold-tone accents',
      'Timeless luxury design',
    ],
    materials: 'Cultured pearls with gold-tone settings',
    care: 'Store pearls separately, avoid perfume contact, wipe gently after wearing.',
    options: ['Pearl & Gold', 'Luxury Collection Box'],
    images: [
      '/images/lisa-marie-theck-pxg9jOgPzK4-unsplash.jpg',
      '/images/brian-wangenheim--5T5yMvZ2-E-unsplash.jpg',
      '/images/theresa-ude-01hjEW7Hc-8-unsplash.jpg',
    ],
    featured: true,
  },
  {
    name: 'VINTAGE CHARM NECKLACE',
    price: '₦195,000',
    category: 'Necklaces',
    story: 'Vintage Revival',
    material: 'Antique brass',
    description: 'A charming vintage-inspired necklace that tells a story of timeless beauty and classic elegance.',
    details: [
      'Vintage-inspired design',
      'Antique brass finish',
      'Unique charm details',
      'Classic chain length',
    ],
    materials: 'Antique brass with vintage charm accents',
    care: 'Polish occasionally with brass cleaner, store in dry environment.',
    options: ['Antique Brass', 'Vintage Box'],
    images: [
      '/images/julie-sd--Njp0M9Rzhc-unsplash.jpg',
      '/images/edgar-soto-o87CUS_uDiQ-unsplash.jpg',
      '/images/mayank-gehlot-lsxBmX8Hmwc-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'CONTEMPORARY CUFF BRACELET',
    price: '₦145,000',
    category: 'Bracelets',
    story: 'Modern Edge',
    material: 'Brushed metal',
    description: 'A bold contemporary cuff that makes a statement with its clean lines and modern aesthetic.',
    details: [
      'Open cuff design',
      'Brushed metal finish',
      'Adjustable sizing',
      'Contemporary style',
    ],
    materials: 'Brushed metal alloy with modern finish',
    care: 'Clean with soft cloth, avoid harsh chemicals.',
    options: ['Brushed Metal', 'Modern Box'],
    images: [
      '/images/pexels-vedat-28933799.jpg',
      '/images/pexels-vedat-29043373.jpg',
      '/images/pexels-sheilabox-235376934-12184920.jpg',
    ],
    featured: false,
  },
  {
    name: 'CELESTIAL MOON EARRINGS',
    price: '₦285,000',
    category: 'Earrings',
    story: 'Celestial Collection',
    material: 'Silver & moonstone',
    description: 'Ethereal earrings inspired by the moon and stars, featuring delicate moonstone accents that catch the light beautifully.',
    details: [
      'Celestial moon design',
      'Moonstone accent details',
      'Silver-tone setting',
      'Ethereal and elegant',
    ],
    materials: 'Silver-tone alloy with moonstone accents',
    care: 'Store carefully to protect moonstone, clean gently.',
    options: ['Silver & Moonstone', 'Celestial Box'],
    images: [
      '/images/muhammad-taha-ibrahim-DWcGIvmI30Y-unsplash.jpg',
      '/images/carlos-esteves-1MWbwTaeJIA-unsplash.jpg',
      '/images/michael-kyule-sjnV1w7TtNE-unsplash.jpg',
    ],
    featured: false,
  },
  {
    name: 'INFINITY LOVE SET',
    price: '₦420,000',
    category: 'Jewellery Sets',
    story: 'Eternal Love',
    material: 'Rose gold tone',
    description: 'A romantic jewelry set featuring infinity symbols, perfect for expressing eternal love and commitment.',
    details: [
      'Infinity symbol design',
      'Rose gold tone finish',
      'Matching necklace and bracelet',
      'Symbol of eternal love',
    ],
    materials: 'Rose gold-tone alloy with infinity motifs',
    care: 'Store in soft pouch, avoid contact with perfumes.',
    options: ['Rose Gold Set', 'Love Collection Box'],
    images: [
      '/images/pexels-gabriela-brasiliano-515209300-32225451.jpg',
      '/images/pexels-howard-chin-1677264-5564051.jpg',
      '/images/pexels-ben-iwara-1033992193-27152278.jpg',
    ],
    featured: true,
  },
]

const fallbackTimestamp = '2026-06-30T00:00:00.000Z'

export const fallbackProducts: ProductData[] = seedProducts.map((product, index) => ({
  ...product,
  _id: `fallback-${index + 1}`,
  createdAt: fallbackTimestamp,
  updatedAt: fallbackTimestamp,
}))

export function getFallbackProducts(category?: string | null) {
  if (!category || category === 'All') {
    return fallbackProducts
  }

  return fallbackProducts.filter((product) => product.category === category)
}

export function getFallbackProductById(id: string) {
  return fallbackProducts.find((product) => product._id === id) ?? null
}
